// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu2APFgN0950eJxSwk7B5ECTqOXQ2t7mA',
    appId: '1:736187335483:web:747b99a096419427aeed1e',
    messagingSenderId: '736187335483',
    projectId: 'palacehr-8a851',
    authDomain: 'palacehr-8a851.firebaseapp.com',
    storageBucket: 'palacehr-8a851.firebasestorage.app',
    measurementId: 'G-7DEBSVZRBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf5PPFEapVEj6ge04WylJdxLVopb45yuQ',
    appId: '1:736187335483:android:cdf5d6fac9cdc720aeed1e',
    messagingSenderId: '736187335483',
    projectId: 'palacehr-8a851',
    storageBucket: 'palacehr-8a851.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVAWAefISSRmISwc2XIbLb-L9fUISniOQ',
    appId: '1:736187335483:ios:00c6002ba15c573daeed1e',
    messagingSenderId: '736187335483',
    projectId: 'palacehr-8a851',
    storageBucket: 'palacehr-8a851.firebasestorage.app',
    iosBundleId: 'com.palace.hr.mosalah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVAWAefISSRmISwc2XIbLb-L9fUISniOQ',
    appId: '1:736187335483:ios:57677db0eae869a7aeed1e',
    messagingSenderId: '736187335483',
    projectId: 'palacehr-8a851',
    storageBucket: 'palacehr-8a851.firebasestorage.app',
    iosBundleId: 'com.example.palaceHr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu2APFgN0950eJxSwk7B5ECTqOXQ2t7mA',
    appId: '1:736187335483:web:bb3e152c81a036d7aeed1e',
    messagingSenderId: '736187335483',
    projectId: 'palacehr-8a851',
    authDomain: 'palacehr-8a851.firebaseapp.com',
    storageBucket: 'palacehr-8a851.firebasestorage.app',
    measurementId: 'G-5M3ZNLYQPE',
  );
}
